# Stage 1: Build the React application
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY .env .env
RUN npm install

COPY . .

RUN npm run build

# Stage 2: Serve the React application using nginx
FROM nginx:alpine

# Copy the built React app from the builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80 to serve the application
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]