apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-backend.fullname" . }}-secrets
  namespace: default
type: Opaque
data:
{{- range $key, $value := .Values.dbSecrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
  DATABASE_SERVICE: {{ printf "%s-postgresql" .Release.Name | b64enc }}