name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.frontend -t aashishlohar/todos-frontend:0.1.2 .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/todos-frontend:0.1.2'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          output: trivy-result.txt

      - name: Check Trivy result file
        run: cat trivy-result.txt

      - name: Push Docker image
        if: success()
        run: |
          docker push aashishlohar/todos-frontend:0.1.2

  publish-helm-chart:
    runs-on: ubuntu-latest
    needs: build-scan-push
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Set up Helm
      #   uses: azure/setup-helm@v4
      #   with:
      #     version: v3.14.4
      - name: Helm Dependencies update
        run: |
          helm dependency update ./react-fastapi-todos-chart

      - name: Package umbrella chart
        run: |
          helm package ./react-fastapi-todos-chart

      - name: Create Helm repo index
        run: |
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
